### ISSUE TITLE
Pre-signed UploadPart - Exposed Headers - ETag is not exposed

### ISSUE THREAD

**Issue by rubencfu** [adobe/S3Mock#1023]
So here is my problem:

I created presigned urls to upload parts of a multipart upload from **client-side** (browser), but when I need to retrieve the **ETag** from those responses, I can't access them because ETag header is not exposed and there is no way (as far as I know) to configure CORS **Access-Control-Expose-Headers** with S3Mock (**PutBucketCorsCommand** is not availabe neither).

So, is there any way to achieve this at the moment, or should I wait for a commit that implements this? Maybe ETag should be always exposed as default configuration?

Thanks! I will gladly help or contribute if someone guides me or gives me a hint of what to do.

**Comment by afranken** [comment]
@rubencfu thanks for raising this issue.
I allowed all headers for CORS in the linked PR. Let me see if I can add some tests as well, then I'll release. :)

**Comment by rubencfu** [comment]
Thanks! Glad it helped, and thank you again for your amazing work here!

I will create more issues if I encounter more problems, but I don't think so, everything works like a charm so far.

**Comment by afranken** [comment]
@rubencfu I had problems pushing releases to hub.docker.com, but **finally** got those resolved this week.
I released 2.12.1 yesterday which includes this fix.

**Comment by rubencfu** [comment]
Thanks!
