### ISSUE TITLE
Continuation token invalidated by delete.

### ISSUE THREAD

**Issue by sparlampe** [adobe/S3Mock#112]
In case the bucket has more than a 1000 objects and I would like to delete them, I list the objects batchwise using nextMarker(v1)/nextContinuationToken(v2). So I request a batch,  delete the batch, request the next batch using the next marker/token, delete it and so on.

The problem I face with the adobe/S3Mock is that the continuation token specifies the offset into the buckets current object list as seen [here](https://github.com/adobe/S3Mock/blob/master/server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java#L360). Obviously if some items before the marker are deleted, the itemstoskip mapped to the marker/continuation token is invalidated.

A correct implementation should return items starting next after the marker in S3 sort oder.
See [marker](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) and [continuation token](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html).

I hacked a solution that works for me [here](https://github.com/sparlampe/S3Mock/commit/e2935e2eff5cc2fcc357f1d8f059343752ee76d5). If a solution based on sorting and mapping the token to a key would be fine, I would be able to submit a PR.

**Comment by agudian** [comment]
Sounds good, we'd be happy to review / merge a solution like that. 👍

**Comment by 412b** [comment]
@sparlampe @agudian any plans to approach and finish this one? there's also a problem with `startAfter` in case of exact key (used in `startAfter`) missing.
I can protentially come up with a PR fixing both, if nobody has time etc.

**Comment by agudian** [comment]
@412b: as we didn't hear back from @sparlampe, yet, I'd say a PR by yourself would be very welcome :)

**Comment by sparlampe** [comment]
I am sorry folks I had to turn to another project and have had no time so far to get back to this issue.
