### ISSUE TITLE
Support for checksumAlgorithm

### ISSUE THREAD

**Issue by miguelfteixeira** [adobe/S3Mock#1123]
While using `checksumAlgorithm` as part of the `PutObjectRequest.builder()` I've noticed that when I do a `getObject` operation using `S3Mock` not only I don't have access to the generated checksum (via `response.response().checksumSHA256()`) but also the `response.contentEncoding` is set to `aws-chunked`. Resulting in not being able to call `ImageIO.read(response)` when I call `PutObject` with `checksumAlgorithm`. 

Everything works as expected when I remove the call to `checksumAlgorithm` or I use a real S3 Client, as in, `response.contentEncoding` is `null` and `ImageIO.read(response)` works.

It's the first I use this library and I've no experience with Kotlin (this is an existing project, I've just added the `checksumAlgorithm`). Is there any plans to provide support for this operation?

**Comment by afranken** [comment]
@miguelfteixeira checksums are indeed currently not supported in S3Mock.

it should be possible to add support in a future release, let me look into it.

**Comment by afranken** [comment]
Looked into this a bit.
First I thought that the S3 backend would need to calculate the checksum, but it's actually the client that calculates the checksum and then sends it to the backend - as part of the request body.

When uploading the sample file
ttps://github.com/adobe/S3Mock/blob/main/integration-tests/src/test/resources/sampleFile.txt

the body looks like this:
```
24
## sample test file ##

demo=content
0
x-amz-checksum-crc32:I6zdvg==

```

I'll have to test with more data to evaluate the pattern and build an inputstream similar to `com.adobe.testing.s3mock.util.AwsChunkedDecodingInputStream` where we skip the bytes we do not want to persist as binary data in the backend, and parse the checksum so we can return it in the API for later requests.
