### ISSUE TITLE
Multipart copy ignores metadata

### ISSUE THREAD

**Issue by mattelacchiato** [adobe/S3Mock#124]
When copying an object as multipart, the explicitly provided metadata gets lost:
```
PUT /cxir/163/164/165/166/167/168/169/170/171172.n

amz-sdk-invocation-id:d4ff771a-4244-db72-6e98-b2954d58d39e
amz-sdk-retry:0/0/500
content-length:0
content-type:application/octet-stream
etag:3e67cd32c281703a4be7a3c688e6b88e-5
host:localhost:9090
last-modified:Tue Jan 29 15:21:17 CET 2019
user-agent:aws-sdk-java/1.11.236 Linux/4.19.16-1-MANJARO OpenJDK_64-Bit_Server_VM/25.192-b26 java/1.8.0_192 scala/2.12.7 groovy/2.4.3 com.amazonaws.services.s3.transfer.TransferManager/1.11.236
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-copy-source:/qffMqtr/161162.zq3t
x-amz-date:20190129T142117Z
x-amz-meta-md5:70d404caafd043fe9b791860bef75652
x-amz-metadata-directive:REPLACE
```

The metadata (`x-amz-meta-md5:70d404caafd043fe9b791860bef75652`) is not available on the destination object. As far as I can see in the code, there's no metadata handling at all for multipart copies.

I am setting the metadata explicitly, since the implicit metadata copy does not work for multipart copies:
```
        // (see also https://github.com/aws/aws-sdk-java/issues/367)
        val newMetadata = new ObjectMetadata()
        newMetadata.setUserMetadata(metadata.getUserMetadata)
        copyObjectRequest.setNewObjectMetadata(metadata)
```

**Comment by agudian** [comment]
That might very well be a gap in the existing implementation. Would you be up to contribute that?

**Comment by mattelacchiato** [comment]
Sorry, this time, I don't have the capacities for that...

**Comment by agudian** [comment]
Fixed by @ChaithanyaGK

**Comment by ChaithanyaGK** [comment]
Copying of metadata during Multipart copy is not yet supported in S3. Once it is supported, we can make changes in S3Mock for that accordingly.

1. https://github.com/aws/aws-sdk-java/issues/367
2. https://github.com/aws/aws-cli/issues/1145

cc: @mattelacchiato
