### ISSUE TITLE
HEAD request to pre-signed GET URL should return forbidden

### ISSUE THREAD

**Issue by c24w** [adobe/S3Mock#125]
This is a bit of a niche one, but it caused a discrepancy in our tests vs reality, so still worth flagging up.

`curl -I https://s3-mock/bucket/file?X-Amz-Algorithm=xxx&X-Amz-Credential=xxx&X-Amz-Date=xxx&X-Amz-Expires=xxx&X-Amz-Security-Token=xxx&X-Amz-Signature=xxx&X-Amz-SignedHeaders=host
`

Actual: `200`  
Expected: `403`

It seems this is the real behaviour because the URL is explicitly only pre-signed for `GET` requests ([reference](https://stackoverflow.com/q/27469801/706561)).

**Comment by afranken** [comment]
presigned parameters are currently completely ignored, see also #219.
