### ISSUE TITLE
accessKey and secretKey invalid

### ISSUE THREAD

**Issue by LemuriaX** [adobe/S3Mock#1250]
Hello, I pulled this warehouse. When I ran it, I found that no matter how the accessKey and secretKey are filled, the request will be accepted. How do I set it so that these two values are valid?

**Comment by afranken** [comment]
Hi!
S3Mock will accept any combination of credentials.
Not sure what you want to achieve - you want S3Mock to reject requests with certain credentials?
Cheers,
Arne

**Comment by afranken** [comment]
see also #305 where the requester never replied with an actual use-case.

**Comment by LemuriaX** [comment]
Yes, can the accessKey and secretKey be generated and verified when the client connects. I've looked at the code and it doesn't seem like this part is there now. If I need this, do I have to implement it myself?

**Comment by afranken** [comment]
I'm still wondering what the use-case is...
S3Mock is meant to be used to test your application against a locally running S3 API.
Why do you want S3Mock to fail requests for a certain set of credentials?

**Comment by LemuriaX** [comment]
I plan to transform a file upload service to be compatible with S3, so I need to implement some functions of S3. I spent some time looking at the documentation of aws, it seems that it is not complicated, maybe I can implement the authentication function by myself. Thank you and your code. 😊

**Comment by afranken** [comment]
maybe this is a misunderstanding:

In your service, you use the S3 SDK.
You provide the credentials to your service, so the S3 SDK can read them. It's easiest to just set environment variables:
https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html

When connecting your service to the real S3 API, you need to provide real credentials.
The S3 API will check if the credentials provided are allowed to execute the operations you're attempting (e.g. list bucket, put object, ...)

When connecting against a locally running S3Mock, you can just provide dummy values. That way you don't have to check in credentials, or build your test setup in a way that retrieves real credentials.
S3Mock does not need any credentials, it just accepts requests from any source without checking whether your credentials are actually valid.

**Comment by LemuriaX** [comment]
Thank you for your reply. What I want now is to build a file server. It must be compatible with the S3 API, so that the client can directly use the S3 SDK to connect. For some reasons, I cannot directly use services such as Minio. So now I downloaded the code of s3 mock and tried to make it have authentication function.

**Comment by LemuriaX** [comment]
I don't really use AWS S3 service, I'm currently building an S3 compatible file server

**Comment by afranken** [comment]
ok, I'll close this then.
Good luck implementing yet another S3 mock... ;)

**Comment by skliarie** [comment]
We use S3Mock as quick and dirty lightweight S3 backup server (with retainFilesOnExit: "true").
No need for full-blown S3 server like minio.
The only drawback is lack of authentication enforcement..
Can you add the feature please?
Taking access and secret key from env would be the best. Allow everybody if not specified.

**Comment by afranken** [comment]
@skliarie the AWS SDK does not simply send the IDs to S3Mock. Not sure if it's possible to somehow reconstruct those values from the incoming headers.

Also, please be ware that this application is meant as a temporary store during integration tests.
Sometimes, bugfixes or features need changes to the internal storage format, so there is no guarantee that the internal storage format is compatible with older versions.

**Comment by skliarie** [comment]
Yes, you need to reconstruct request signature, by taking access_key and sign incoming request parameters using secret_key. Then compare signatures.

See python example here:
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTAuthentication.html#RESTAuthenticationExamples

Storage format change is fine, we are not going to upgrade our backup servers easily. Some prudence on your part would be appreciated though ;)
May be put storage version somewhere, assertions, etc..

**Comment by jeacott1** [comment]
+1 for rejecting bad credentials. Even in an integration test environment you need to check your signed requests are actually signed correctly. It's a big missing piece of functionality if this cant be verified.
