### ISSUE TITLE
Self-closing CommonPrefixes on ListObjects causes unexpected behaviour in S3 SDK

### ISSUE THREAD

**Issue by kevinulrich** [adobe/S3Mock#128]
When calling ListObjects (V1 or V2) and filtering to a non-existant prefix, a self-closing CommonPrefixes tag will be returned. That in itself is not necessarily wrong, although it is not mentioned in AWS docs.

```
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult>
   <truncated>false</truncated>
   <Name>mybucket</Name>
   <Prefix>this/does/not/exist/</Prefix>
   <Marker />
   <MaxKeys>1</MaxKeys>
   <IsTruncated>false</IsTruncated>
   <CommonPrefixes />
</ListBucketResult>
```

Now when consumed with the AWS PHP SDK this behaviour will cause the stream-wrapper implementation to assume that when checking for directories via `is_dir` every non-existant key is a directory. Now that's somewhat of an edge case as it is a legacy use option and I guess it's a bad coincidence between the AWS SDK and S3Mock. I have also raised an issue with that repository.

**Comment by afranken** [comment]
Sorry, it's been a while. :(
This was just fixed, see #257 / #258
