### ISSUE TITLE
Should sync path fragment

### ISSUE THREAD

**Issue by bamthomas** [adobe/S3Mock#13]
Hi all, 

First of all thank you for the fix of the issue https://github.com/adobe/S3Mock/issues/8 

I'm using the S3Mock that I find very convenient for integration tests and I have a new case that fails :

    @Rule
    public TemporaryFolder folder= new TemporaryFolder();
    @Test
    public void shouldSyncPathFragment() {
      final File uploadFile = new File(UPLOAD_FILE_NAME);

      s3Client.createBucket(BUCKET_NAME);
      s3Client.putObject(new PutObjectRequest(BUCKET_NAME, UPLOAD_FILE_NAME, uploadFile));

      final TransferManager tm = createDefaultTransferManager();
      tm.downloadDirectory(BUCKET_NAME, "src", folder.getRoot());
      tm.shutdownNow(false);

      assertThat(new File(folder.getRoot() + UPLOAD_FILE_NAME).exists(), is(true));
    }

That is when objects are under `a/s3/path` then downloading `a` key should make like a `rsync` with remote directory. That case is working with a real S3 remote. With the mock I get a 

**EDIT** : use of downloadDirectory instead of download method. There is no 404 but the assertion fails.

Is it a new feature for S3Mock ?

**Comment by agudian** [comment]
Yes, it seems like we don't have that part of the API covered, yet. Would you be open to investigate the exact API calls that are performed there and create a PR with the extension?

**Comment by bamthomas** [comment]
I'm going to try to have a look even if I'm not very familiar with spring boot and the implemented stack ;)

**Comment by bamthomas** [comment]
My mistake, multiple download actually works as the client downloads the list returned by the

    GET /mydemotestbucket/?prefix=src&delimiter=%2F&encoding-type=url 

with regular download requests. 
So this test is already green :

    @Rule
    public TemporaryFolder folder= new TemporaryFolder();

    @Test
    public void shouldSyncPathFragment() throws Exception {
      final File uploadFile = new File(UPLOAD_FILE_NAME);
      s3Client.createBucket(BUCKET_NAME);
      s3Client.putObject(new PutObjectRequest(BUCKET_NAME, UPLOAD_FILE_NAME, uploadFile));

      TransferManager tm = createDefaultTransferManager();
      tm.downloadDirectory(BUCKET_NAME, "src", folder.getRoot()).waitForCompletion();
      tm.shutdownNow(false);

      assertThat(new File(folder.getRoot() + "/" + UPLOAD_FILE_NAME).exists(), is(true));
    }

I close this issue.
