### ISSUE TITLE
S3mock server spin-up with custom credentials

### ISSUE THREAD

**Issue by vineelya** [adobe/S3Mock#139]
I want to spin-up S3Mock with configuration of my own. Also I want to set enablePathAccess=FALSE. Does S3 Mock support hosting files in this fashion (virtual file style). In that case , I will be addressing the resources like this (http://bucket-name.hostname:port/key).
Thanks in advance.

**Comment by agudian** [comment]
You can find the configuration options in class `S3MockApplication`.

Using pathStyleAccess is not supported right now, though. It would be an interesting thing to add, though. It would require running Docker containers with a specific setup to bind internal DNS names properly, and executing the tests from within a Docker container using the same Docker network.

**Comment by agudian** [comment]
I've created  #144 to track adding support for non-path style access.

If you have more specific ideas what you want to configure, please reopen this ticket and edit the description.
