### ISSUE TITLE
Logback conflict with log4j

### ISSUE THREAD

**Issue by hjloliveira** [adobe/S3Mock#141]
I cannot start the server due to multiple SLF4J bindings:

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Herson_Oliveira/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Herson_Oliveira/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]`

I've tried to exclude that logback dependency but it causes all sort of other problems. Any ideas?

**Comment by agudian** [comment]
The S3 mock server component comes with `spring-boot-starter-logging`, which pulls in `logback-classic` and `log4j-to-slf4j`. Either you don't add `slf4j-log4j12` to your test classpath, or you exclude the former two depdendencies from the `s3mock` dependency that you reference.

You can also check with `mvn depdendency:tree` to see where unwanted dependencies come from.

(closing this, as I hope that answers your question. Please reopen if you think something needs to be changed in S3Mock)

**Comment by AlJohri** [comment]
Quick follow up question, is it safe to exclude `spring-boot-starter-logging`? I'm not super familiar yet with java dependency management, but I thought that all the dependencies listed in `mvn dependency:tree` or `mvn dependency:list` were required?

```
[INFO] |  |  +- org.springframework.boot:spring-boot-starter:jar:2.6.2:test
[INFO] |  |  |  +- org.springframework.boot:spring-boot:jar:2.6.2:test
[INFO] |  |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.6.2:test
[INFO] |  |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.6.2:test
[INFO] |  |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.9:test
[INFO] |  |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.9:test
[INFO] |  |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.0:test
[INFO] |  |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.0:test
[INFO] |  |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.32:test
```

If that's not the case, perhaps it makes sense to make the exclusion in S3Mock's `pom.xml` itself?
