### ISSUE TITLE
putObject doesn't support tagging

### ISSUE THREAD

**Issue by raptros** [adobe/S3Mock#142]
AWS documentation specifies that putObject requests allow passing initial tagging via the x-amz-tagging header:
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html
> Specifies a set of one or more tags to associate with the object. These tags are stored in the tagging subresource that is associated with the object.
> To specify tags on an object, the requester must have s3:PutObjectTagging included in the list of permitted actions in their IAM policy.
> For more information about adding tags to an object, see Object Tagging Management in the Amazon Simple Storage Service Developer Guide.
> Type: String
> Default: None
> Constraints: The encoding for tags is URL query parameter encoding. The maximum size of this header is 2 KB. 

I think the fix should be fairly simple; I'm planning to submit a PR once I can sign the CLA.

**Comment by agudian** [comment]
Awesome, that would be much appreciated 👍

**Comment by agudian** [comment]
Fixes by your own PR. Thanks!
