### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [adobe/S3Mock#158]
Hi
The following lines have cryptographic API misuses. <br> File name => server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java: Line number => 764: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => server/src/main/java/com/adobe/testing/s3mock/util/HashUtil.java: Line number => 70: API name => MessageDigest:Unexpected call to method reset on object of type java.security.MessageDigest. Expect a call to one of the following methods digest,update<BR> File name => server/src/main/java/com/adobe/testing/s3mock/domain/FileStore.java: Line number => 830: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR>

**Comment by agudian** [comment]
As intended.
