### ISSUE TITLE
Support S3AsyncClient from software.amazon.awssdk:s3

### ISSUE THREAD

**Issue by vlbaluk** [adobe/S3Mock#1613]
Are you going to put S3AsyncClient implementation alongside synchronous in the near future? We will switch to the S3 Async client, but rewriting tests is blocked.😐

**Comment by afranken** [comment]
@vlbaluk did you get an AsyncClient to work in your tests? It should be easily possible to do so.
I can look into adding Async versions to the test infrastructure in one of the next releases for convenience.
