### ISSUE TITLE
Avoid using Spring AutoConfiguration

### ISSUE THREAD

**Issue by theodiefenthal** [adobe/S3Mock#175]
I want to use the S3Mock JUnit4 rule which starts the s3 mock server in background.
Sadly, my project depends on a library which in turn is still using GSON 2.2.2.

Due to springs classpath scanning in combination with EnableAutoConfiguration, the s3 mock server detects GSON in the classpath and tries to call some methods on it, not yet existant in the old GSON version. The following error appears:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration$StandardGsonBuilderCustomizer.customize(GsonAutoConfiguration.java:90)

The following method did not exist:

    com.google.gson.GsonBuilder.setLenient()Lcom/google/gson/GsonBuilder;

The method's class, com.google.gson.GsonBuilder, is available from the following locations:

    jar:file:/C:/Users/dev/.m2/repository/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar!/com/google/gson/GsonBuilder.class

It was loaded from the following location:

    file:/C:/Users/dev/.m2/repository/com/google/code/gson/gson/2.2.2/gson-2.2.2.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of com.google.gson.GsonBuilder
```
=> I was able to "solve" this issue by upgrading GSON to a more recent version and my library didn't complain about it. But in general, I think its not a good approach for a library being useable in other projects to enable spring auto configuration and play around with the classpath of the entire application...

**Comment by xfornesa** [comment]
Probably we should split the project in two parts: S3Mock (no framework references) and S3mock-springboot-autoconfiguration (with framework references).
There are several projects that does that, e.g: https://github.com/PebbleTemplates/pebble . In this example they are using the same repo and split the code as modules.

**Comment by aheritier** [comment]
It might be great. I have a similar issue with my tests failing as soon as I had s3mock in my classpath. S3MockApplication is trying to start with my project classpath and fails (a strange issue with liquibase)

**Comment by timoe** [comment]
Well, the issue here is that, as of now, running the HTTP server is tightly coupled to Spring Boot. 

There are lots of issues with these auto-configs which are caused by the fact that we use spring boot. Maybe it's a better idea to go for something else than Spring...

**Comment by agudian** [comment]
How about using Quarkus... we‘d have a super fast and small Docker container, and a CDI / MicroProfile based codebase for the same-JVM mode... I wonder how that would turn out...

**Comment by timoe** [comment]
> How about using Quarkus... 

yepp ;)

**Comment by vicmosin** [comment]
So is there any workaround for issue?

**Comment by afranken** [comment]
S3Mock 2.2.0 was just released that now includes support for [TestContainers](https://www.testcontainers.org/).
If there is a possibility of running Docker during your build, I would highly suggest migrating to TestContainers.

Using S3MockApplication directly or through one of the unit test modules will always have the risk of breaking because of dependencies that are pulled in by the application that is being tested, and auto configration that is added through Spring Boot updates in the S3Mock.

Using Docker in your tests will insulate both applications dependencies and application life cycles.
