### ISSUE TITLE
S3Mock fails when Server Side Encryption is set without a key

### ISSUE THREAD

**Issue by MatthewMiele** [adobe/S3Mock#190]
Currently if you try to use the mock with server side encryption (`aws:kms`) without specifying a key the mock fails. This is seems to be due to the header not being set when a key is not specified `"x-amz-server-side-encryption-aws-kms-key-id"`

Example test command
```
aws --endpoint-url http://localhost:9090  s3api put-object --bucket test-bucket --key test-file --body test.txt --no-sign-request --server-side-encryption aws:kms
```
Error
```
c.a.testing.s3mock.KmsValidationFilter   : Caught exception

java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[na:na]
        .....
```
The S3 docs state a key is optional. If no key is provided Amazon S3 assumes the AWS managed CMK.

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingKMSEncryption.html

> **Note**
When you upload an object, you can specify the AWS KMS CMK using the x-amz-server-side-encryption-aws-kms-key-id header. If the header is not present in the request, Amazon S3 assumes the AWS managed CMK. Regardless, the AWS KMS key ID that Amazon S3 uses for object encryption must match the AWS KMS key ID in the policy, otherwise Amazon S3 denies the request.

**Comment by agudian** [comment]
Nicely spotted! Would be up to create a PR to fix this?

**Comment by timoe** [comment]
>   If the header is not present in the request, Amazon S3 assumes... 

right but doesn't that mean, that, if you pass the header, you have to pass a key-ref as well. The other way round, if you pass only the header but not a key-ref, this is an invalid request? 

So, I would assume S3 Mock has to return 400 BAD_REQUEST here.

**Comment by timoe** [comment]
Well, I was wrong. Doc says
> If you specify x-amz-server-side-encryption:aws:kms, but don't provide x-amz-server-side- encryption-aws-kms-key-id, Amazon S3 uses the AWS managed CMK in AWS KMS to protect the data.

so, not passing a key-ref should go through

**Comment by agudian** [comment]
Timo fixed it with #194 👍

**Comment by MatthewMiele** [comment]
Thanks for the fix @timoe ! Would it be possible to make a release? (specially a new docker image on docker hub). Thanks again

**Comment by timoe** [comment]
I'll do a release tomorrow, Friday is a good day for releases ;)
