### ISSUE TITLE
listMultipartUploads with setPrefix

### ISSUE THREAD

**Issue by PaulGregory50** [adobe/S3Mock#192]
I have an s3mock bucket with stale multipart uploads.

When I listMultipartUploads with a prefix the prefix is ignored. I see all keys. 

Snippet of Java code:

ListMultipartUploadsRequest allMultipartUploadsRequest = new ListMultipartUploadsRequest("myBucket")  ;
		allMultipartUploadsRequest.setPrefix("myPrefix") ;		
        MultipartUploadListing multipartUploadListing = client.listMultipartUploads(allMultipartUploadsRequest);
        List<MultipartUpload> uploads = multipartUploadListing.getMultipartUploads();

**Comment by timoe** [comment]
fixed by https://github.com/adobe/S3Mock/pull/193
