### ISSUE TITLE
NullPointerException running the junit5 extension test for SDK V2 in Scala

### ISSUE THREAD

**Issue by krunalvora** [adobe/S3Mock#196]
I am trying to run the S3Mock Junit5 extension test for SDK V2 in Scala.

```
object S3MockAdobeSpec {
  @RegisterExtension
  val S3_MOCK: S3MockExtension = S3MockExtension.builder.silent.withSecureConnection(false).build
  private val BUCKET_NAME = "mydemotestbucket"
  private val UPLOAD_FILE_NAME = "src/test/resources/sampleFile.txt"
}

class S3MockAdobeSpec {
  final private val s3Client = S3MockAdobeSpec.S3_MOCK.createS3ClientV2

  /**
   * Creates a bucket, stores a file, downloads the file again and compares checksums.
   *
   * @throws Exception if FileStreams can not be read
   */
  @Test
  @throws[Exception]
  def shouldUploadAndDownloadObject(): Unit = {
    val uploadFile = new File(S3MockAdobeSpec.UPLOAD_FILE_NAME)
    s3Client.createBucket(CreateBucketRequest.builder.bucket(S3MockAdobeSpec.BUCKET_NAME).build)
    s3Client.putObject(PutObjectRequest.builder.bucket(S3MockAdobeSpec.BUCKET_NAME).key(uploadFile.getName).build, RequestBody.fromFile(uploadFile))
    val response = s3Client.getObject(GetObjectRequest.builder.bucket(S3MockAdobeSpec.BUCKET_NAME).key(uploadFile.getName).build)
    val uploadFileIs = new FileInputStream(uploadFile)
    val uploadHash = HashUtil.getDigest(uploadFileIs)
    val downloadedHash = HashUtil.getDigest(response)
    uploadFileIs.close()
    response.close()
    assertEquals(uploadHash, downloadedHash, "Up- and downloaded Files should have equal Hashes")
  }
}
```

I am not sure whether I need to start the S3Mock server programmatically beforehand even when trying the JUnit5 method.

I get a NullPointerException at S3MockStarter.getHttpPort with a null value for S3MockStarter.

Could someone help me with this?

Also, is there support for AsyncRequestBody for a putObject with SDK V2?

@timoe

**Comment by tinder-krunalvora** [comment]
@agudian @timoe Any ideas on what I might be doing wrong here? Appreciate the suggestions!

**Comment by krunalvora** [comment]
@agudian @timoe Any ideas on what I might be doing wrong here? Appreciate the suggestions!

**Comment by ChaithanyaGK** [comment]
> I am not sure whether I need to start the S3Mock server programmatically beforehand even when trying the JUnit5 method.

@krunalvora No need to start S3Mock server beforehand when trying the Junit5 method.
I'm not familiar with scala. Could you please share your scala project, let me see whether I can help.

**Comment by krunalvora** [comment]
Thanks @ChaithanyaGK 
I will share the scala project. 

In the meantime, if I am using the programmatically running the server method, can I create AWS S3 clients using the AWS SDK and expect it to work with the S3Mock endpoint or I need to use the S3Mock library to create the S3 client?
And is there support for AsyncS3Client?

**Comment by timoe** [comment]
thanks for reporting this @krunalvora.

Regarding
> Also, is there support for AsyncRequestBody for a putObject with SDK V2?

It is not. But: Contributions are always welcome ;) Would you like to file a PR for that?

**Comment by ChaithanyaGK** [comment]
Hi @krunalvora 
>If I am using the programmatically running the server method, can I create AWS S3 clients using the AWS SDK and expect it to work with the S3Mock endpoint

Yes, the only catch is you need to override endpoint to point to the S3Mock endpoint.
Please refer https://github.com/adobe/S3Mock/blob/6a230311a29567cc1148009036bcf84dc0ef2ecd/server/src/test/java/com/adobe/testing/s3mock/its/S3TestBase.java#L107


> Also, is there support for AsyncRequestBody for a putObject with SDK V2?

I believe no additional changes are required in S3Mock to support async flows, they should work out of the box with SDK V2. Below test with AsyncRequestBody is working for me against S3Mock.

But, I may be completely wrong here.

```
  @Test
  void shouldUploadAsyncTest() {

    CompletableFuture<PutObjectResponse> future = s3AsyncClient.putObject(
        PutObjectRequest.builder()
                        .bucket(BUCKET_NAME)
                        .key(UPLOAD_FILE_NAME)
                        .build(),
        AsyncRequestBody.fromFile(Paths.get(UPLOAD_FILE_NAME))
    );

    future.whenComplete((resp, err) -> {
      try {
        if (resp != null) {
          System.out.println("my response: " + resp);
        } else {
          // Handle error
          err.printStackTrace();
        }
      } finally {
        // Lets the application shut down. Only close the client when you are completely done with it.
        s3AsyncClient.close();
      }
    });

    future.join();
  }
```

**Comment by krunalvora** [comment]
Thanks @ChaithanyaGK for this explanation.

I tried this code snippet:

```
val s3Mock: S3MockApplication = S3MockApplication.start("--http.port=9192")

  val region = Region.US_WEST_2

  val s3ClientV2 = S3Client.builder()
    .region(region)
    .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("foo", "bar")))
    .endpointOverride(URI.create("https://localhost:9192"))
    .httpClient(UrlConnectionHttpClient.builder().buildWithDefaults(
      AttributeMap.builder().put(TRUST_ALL_CERTIFICATES, java.lang.Boolean.TRUE).build()
    ))
    .build()

s3ClientV2.listBuckets()
```


Fails with an exception:
`Exception in thread "main" software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Unrecognized SSL message, plaintext connection?`

Am I starting the S3Mock server incorrectly?

**Comment by ChaithanyaGK** [comment]
It should be `http` end-point not `https` as you've started the application with http port 

`endpointOverride(URI.create("http://localhost:9192"))`

**Comment by afranken** [comment]
@krunalvora could you get this working?

You could also try running S3Mock in Docker during your tests.
Support for [TestContainers](https://www.testcontainers.org/) was added in S3Mock 2.2.0, a Docker container for general usage was added way before that.
If there is a possibility of running Docker during your build, I would highly suggest migrating to TestContainers.
