### ISSUE TITLE
CopyObject with Metadata directive "REPLACE" does not update system metadata

### ISSUE THREAD

**Issue by raymondregrello** [adobe/S3Mock#2005]
Repro steps:
1. Create object A using `PutObject` with "Content-Disposition" set to ""
2. Call `CopyObject` with src and dst pointing to object A, metadata directive set to "REPLACE" and "Content-Disposition" set to "attachment"

Result:
`operation error S3: CopyObject, https response error StatusCode: 400, RequestID: , HostID: , api error InvalidRequest: This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.`

Expected:
The object should be updated in place with the new "Content-Disposition" value

**Comment by afranken** [comment]
@raymondregrello 
does this work against the S3 API?
"Content-Disposition" is not part of the objects metadata, so S3 should return the same error.

**Comment by raymondregrello** [comment]
@afranken Thanks for taking a look at this!

It does work with the S3 API. "Content-Disposition" is part of the system metadata that users can modify:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#SysMetadata

**Comment by raymondregrello** [comment]
Thank you! :)
