### ISSUE TITLE
Using S3Mock with dot net 3.1 project gives an error as Name or Service not know 

### ISSUE THREAD

**Issue by AnushaErrabelli** [adobe/S3Mock#205]
Advance thank you for helping!

my docker-compose is

s3mock: 
    image: adobe/s3mock
    ports:
      - "9090:9090"
    environment:
     - initialBuckets=fin-disc-dev-files
     - AWS_ACCESS_KEY_ID=foobar
     - AWS_SECRET_ACCESS_KEY=foobar

Please let me know do I need add any environment variables extra?

**Comment by agudian** [comment]
Without knowing more about the error message, it sounds like you have to configure your client to use pathStyleAccess (as by default, it would try to call `http://<bucket-name>.localhost:9090`, which can’t be resolved to an ip-address (and which is not in control of the started Docker container).

If that’s not helpful, please let us know a bit more about what call you’re trying to make and how your client is configured.

**Comment by AnushaErrabelli** [comment]
@agudian thank you for immediate response.  I have configured my client to use my app settings file parameters and in it giving the parameters and data like below
"AWS": {
      "ServiceURL": "http://s3mock.localhost:9090",
      "ForcePathStyle":true
    },

I feel  docker is  not establishing the connection with S3. Please let me know if you need any other information 

///(url
<img width="779" alt="Screen Shot 2020-01-13 at 12 55 35 PM" src="https://user-images.githubusercontent.com/37459695/72279620-82c5ed80-3604-11ea-8b1a-5fb53c62be28.png">
)

Note: I tried giving bucket name instead of service it's not working, thank you!!

**Comment by agudian** [comment]
The endpoint (ServiceURL) needs to be configured as `http://localhost:9090` in your case.

**Comment by AnushaErrabelli** [comment]
@agudian thank you again!! I tried it already using this endpoint, it's not working

**Comment by agudian** [comment]
Then it’s probably something with the Docker setup (verify that you can reach the S3 mock endpoint from where you start your application, eg. through a command-line or using a browser going to http://localhost:9090/favicon.ico ), or something with the config of the AWS .net library..?

If you see the S3mock starting, you should be all good there. No special config is required for it (you can also leave out the AWS_* env variables).

**Comment by AnushaErrabelli** [comment]
@agudian, I can connect to the s3 end point from docker container. I tested it with aws cli from docker container, it's working with http://s3mock:9090.  AWS.net library refuses connection at some point, also it's not working with https://s3mock:9191 (default https://localhost:9191 also not working).

**Comment by davidcuevastransfer** [comment]
@AnushaErrabelli Did you manage to sort this? I reckon i'm having the same problem with the S3Mock docker container.

I'm using S3Mock for an SpringBoot Integration test and i am getting a 

> Caused by: java.net.UnknownHostException: <bucketname>.<host>

Would be nice to have some light shed on this

**Comment by AnushaErrabelli** [comment]
@davidcuevastransfer Sorry, I did not see the notification. I'm able to solve the issue by providing fake aws credentials  during api spin up, before I was providing from S3mock env. 

If you provide aws credentials from docker-compose spring boot service it might work! if not please let me know, thanks you!

**Comment by afranken** [comment]
Closing this as the original author was able to solve their problem.
