### ISSUE TITLE
S3mock ignores `Content-MD5` header

### ISSUE THREAD

**Issue by gh2k** [adobe/S3Mock#208]
The [docs for putObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#API_PutObject_RequestSyntax) describe the `Content-MD5` header which should verify the uploaded data, and return an error if the supplied base64-encoded md5 hash does not match that of the received data.

It looks like this parameter is ignored. I can pass anything here and the upload still works.

It would be very helpful if support for this was implemented.

**Comment by timoe** [comment]
Thanks for reporting. Would you like to file a PR for that, contributions are always welcome.
