### ISSUE TITLE
s3 conditional writes

### ISSUE THREAD

**Issue by sullis** [adobe/S3Mock#2084]
does S3Mock implement s3 conditional writes?

August 2024:
https://aws.amazon.com/about-aws/whats-new/2024/08/amazon-s3-conditional-writes/

August 2024:
https://www.tigrisdata.com/blog/s3-conditional-writes/

**Comment by afranken** [comment]
S3Mock currently does not support conditional writes, conditional reads only in some cases.
See #829

**Comment by afranken** [comment]
I released https://github.com/adobe/S3Mock/releases/tag/4.0.0 which now properly implementes conditional writes and reads.
