### ISSUE TITLE
Missing documentation for mocks' file system structure

### ISSUE THREAD

**Issue by giacomomagini** [adobe/S3Mock#220]
Hello!
I had to look into the code to understand what's the filesystem structure for adding object mocks. It'd be nice to have it documented.

Cheers,

Giacomo

**Comment by afranken** [comment]
I will document the directory layout properly soon (was requested a while ago here, but I wanted to refactor the way we store files first before doing the documentation, which I just finished in 2.5.0), but of the top of my head it should look like this:

```Storage of Buckets:
<root>/<bucket-name>

Storage of Bucket metadata:
<root>/<bucket-name>/bucketMetadata
(contains the "key" -> "uuid" dictionary for all objects uploaded to this bucket)

Storage of objects
<root>/<bucket-name>/<uuid>

Storage of object (meta)data
<root>/<bucket-name>/<uuid>/binarydata
<root>/<bucket-name>/<uuid>/metadata
<root>/<bucket-name>/<uuid>/partdata
<root>/<bucket-name>/<uuid>/<partNo>.part
```

this will finally be done soon in the `README.md`, promise! :)
