### ISSUE TITLE
Provide a way to override server.ssl properties programmatically

### ISSUE THREAD

**Issue by vlsi** [adobe/S3Mock#230]
I want to start a mock with a certificate from my own keystore.

It looks like there is a couple of issues with that:

1. `S3MockExtension.Builder` does not allow free-form properties to be passed. It would be nice to have `withProperty(name, value)` method there.

2. `server.ssl` properties are declared in `application.properties`, so the values there win even if the property is passed via `SpringApplicationBuilder#properties`. See https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config

https://github.com/adobe/S3Mock/blob/16ec064bf640a9f7b295d5bb2e7ba240f8bf4569/server/src/main/resources/application.properties#L17-L19

What do you think if `server.ssl` values are moved from `application.properties` to `defaults` inside `com.adobe.testing.s3mock.S3MockApplication#start(java.util.Map<java.lang.String,java.lang.Object>, java.lang.String...)` ?

**Comment by agudian** [comment]
Great idea! Feel free to create a PR and we‘ll look at at as soon as possible 🙂👍

**Comment by afranken** [comment]
if I understand correctly, this is fixed with #231. Closing.
