### ISSUE TITLE
aws s3 ls command not showing files under a prefix

### ISSUE THREAD

**Issue by GiltosMx** [adobe/S3Mock#236]
### What is the problem?
I have a bucket, let's call it `generic-bucket`. Inside that bucket, I have written some objects with a prefix. Let's call it `genericPrefix`. Example:
```json
{
    "Contents": [
        {
            "Key": "genericPrefix/my-awesome-s3-object",
            "LastModified": "2020-08-10T20:46:54.000Z",
            "ETag": "aad34a11277550215ac7a7010d3a7ee1",
            "Size": 2492,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "s3-mock-file-store",
                "ID": "123"
            }
        }
    ]
}
```
I know this might be a bug, because I'm not able to list the objects with the prefix `genericPrefix` using this command:
```shell
aws s3 ls generic-bucket/genericPrefix --recursive --human-readable --summarize --endpoint-url http://localhost:9090
```

In a "real" s3 bucket in AWS I get the following output from the command above (minus the `--endpoint-url` argument):
```
2020-08-10 11:28:56    4.8 KiB genericPrefix/my-awesome-s3-object

Total Objects: 1
   Total Size: 4.8 KiB
```

Whereas with the `s3Mock` I'm getting only this:
```

'Prefix'
```

If I remove the `--recursive` argument in the `s3Mock` I get this:
```
                           PRE secFilings/

Total Objects: 0
   Total Size: 0 Bytes
```

So I know that the prefix is there.

In contrast, if I use the following syntax in the `s3Mock`:
```shell
 aws s3api list-objects-v2 --bucket generic-bucket --prefix genericPrefix --endpoint-url http://localhost:9090
```

I do get the list of items under the prefix:
```json
{
    "Contents": [
        {
            "Key": "genericPrefix/my-awesome-s3-object",
            "LastModified": "2020-08-10T20:46:54.000Z",
            "ETag": "aad34a11277550215ac7a7010d3a7ee1",
            "Size": 2492,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "s3-mock-file-store",
                "ID": "123"
            }
        }
    ]
}
```

### Questions
Does this look like a bug? Am I doing something wrong in the syntax?
If it is a bug, I'd love to contribute and try to fix it myself if I can get some pointers around where could be a good place to start in the codebase.

**Comment by agudian** [comment]
There have been several attempts to mimic the S3 behavior regarding prefixes correctly, so I wouldn't be surprised if there were still some cases where it doesn't fit.

In the codebase, you find that logic in `FileStoreController.listObjectsInsideBucketV2` and `listObjectsInsideBucket` - just check where the `prefix` parameter goes from there.

You could start with extending one of the `ListObject*IT` tests with your findings.

**Comment by agudian** [comment]
This could be related as well: #227

**Comment by GiltosMx** [comment]
Thank you for the pointers. I'm slammed at work this week, but I'll take a look during the weekend.

**Comment by afranken** [comment]
Not reproducible.
I'm guessing some change in the last 11 months fixed this problem.

I have  a local folder with a few files and a sub-folder:

```
ls -R
./           ../          cat-1.jpg    cat-2.jpg    cat-3.jpg    cat-4.jpg    test-prefix/ test.json    test.txt

./test-prefix:
./         ../        cat-5.jpg  cat-6.jpg  cat-7.jpg  cat-8.jpg
```

I sync that folder into "my-test-bucket"
`aws s3 sync . "s3://my-test-bucket/" --endpoint-url http://localhost:9090`

I can successfully `ls` the bucket:
```
aws s3 ls my-test-bucket --recursive --human-readable --summarize --endpoint-url http://localhost:9090
2021-07-01 09:28:09  317.8 KiB cat-1.jpg
2021-07-01 09:28:09   54.7 KiB cat-2.jpg
2021-07-01 09:28:09  171.0 KiB cat-3.jpg
2021-07-01 09:28:09   69.9 KiB cat-4.jpg
2021-07-01 12:38:03   31.0 KiB test-prefix/cat-5.jpg
2021-07-01 12:38:03  353.4 KiB test-prefix/cat-6.jpg
2021-07-01 12:38:04  732.0 KiB test-prefix/cat-7.jpg
2021-07-01 12:38:04  227.5 KiB test-prefix/cat-8.jpg
2021-07-01 12:15:45   36 Bytes test.json
2021-07-01 12:15:45    4 Bytes test.txt
2021-07-01 12:26:52   36 Bytes test2.json

Total Objects: 11
   Total Size: 1.9 MiB
```

as well as only the prefix in the bucket:
```
aws s3 ls my-test-bucket/test-prefix --recursive --human-readable --summarize --endpoint-url http://localhost:9090
2021-07-01 12:38:03   31.0 KiB test-prefix/cat-5.jpg
2021-07-01 12:38:03  353.4 KiB test-prefix/cat-6.jpg
2021-07-01 12:38:04  732.0 KiB test-prefix/cat-7.jpg
2021-07-01 12:38:04  227.5 KiB test-prefix/cat-8.jpg

Total Objects: 4
   Total Size: 1.3 MiB
```
