### ISSUE TITLE
[Feature] adding option to configure FileStore root directory

### ISSUE THREAD

**Issue by sujithvbsl** [adobe/S3Mock#25]
Hi

I am using S3Mock for my integration tests. Sometimes on my workplace VM or on the test environment, housekeeping jobs deletes all contents in the /tmp folder. It will be a good feature if we could configure the FileStore root directory instead creating it in default construct.

Thanks,

Sujith

**Comment by timoe** [comment]
Sounds useful, thanks for that suggestion @sujithvbsl. We'd happily review any pull requests. Would you be open to contribute one?

**Comment by ArnoTurelinckx** [comment]
opened a pull request for this
https://github.com/adobe/S3Mock/pull/28
providing a builder for the classrule and the option to provide an argument(root) when running the application
