### ISSUE TITLE
Split test artifacts so users could pull either SDK v1 or SDK v2 dependency

### ISSUE THREAD

**Issue by vlsi** [adobe/S3Mock#255]
Currently, test-common pulls both SDK v1 and SDK v2, which causes excessive classes in autocomplete.

It would be nice to avoid pulling v1 SDK when only v2 is needed even though they are for testing purposes only.

WDYT?

**Comment by agudian** [comment]
That’s a good idea!

**Comment by afranken** [comment]
See comment in the other issue - it is recommended to use the S3Mock Docker container instead of starting the S3Mock directly from your JUnit tests.

The test artifacts will be deprecated and removed in the future.
