### ISSUE TITLE
When using putObject bucket is created rather than object

### ISSUE THREAD

**Issue by jakelamotta** [adobe/S3Mock#262]
I am completely new to S3 so it might be me doing something wrong here but the java AmazonS3Client is behaving very strange with the Docker S3Mock server. So I am using the latest docker image. 

I am using the 1.12.15 version of AmazonS3Client. I am not doing anything advanced yet, just trying to add a file to the bucket I have created (via aws-cli). This is what I do:

`var client = AmazonS3ClientBuilder.standard()                                              .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:9090", "us-east-1")).build();`

 `client.putObject("myBucket", "myKey", new File(myPath));`
            
Doing this results in no new object in "myBucket" but a new bucket called "myKey".

**Comment by afranken** [comment]
@jakelamotta can't reproduce...
See
https://github.com/adobe/S3Mock/blob/main/server/src/test/java/com/adobe/testing/s3mock/its/AmazonClientUploadIT.java#L161
for examples on how to use the mock with the Amazon client.
If you started the S3Mock on the default ports (it seems you did) you can just run all tests in "IT" named classes against that instance.

**Comment by afranken** [comment]
@jakelamotta did this answer your question?

**Comment by afranken** [comment]
@jakelamotta 
I'm guessing your question is answered, then. :)

**Comment by canp1** [comment]
Kind of late to the party but I stumbled upon the same “error” today and wanted to leave the solution to this I discovered. Basically, there are two ways you can access a s3 bucket:
**"normal way":** bucketname.url/filename
**s3mock way (withPathStyleAccessEnabled):** url/bucketname/filename

So I just had to add a property to my client builder in my integration tests.
No real error, only my dumbass not knowing how to use s3...

 ```
public AmazonS3 getAmazonS3Client() { 
    return AmazonS3ClientBuilder
        .standard()
        .withEndpointConfiguration((new AwsClientBuilder.EndpointConfiguration(endpoint, region)))
        .withPathStyleAccessEnabled(true) // Required for S3Mock compatibility
        .build();
  }
```

Hope that helps anyone :)

**Comment by afranken** [comment]
@canp1 yeah, there are a few caveats when using S3Mock, see:
https://github.com/adobe/S3Mock?tab=readme-ov-file#path-style-vs-domain-style-access
