### ISSUE TITLE
Copy object part failures

### ISSUE THREAD

**Issue by wwelling** [adobe/S3Mock#279]
A few issues while testing with multipart upload copy. The copy object part endpoint is not encoding its source key resulting in the source object not being found. The copy object part endpoint is not producing XML and AWS SDK cannot serialize responses from JSON. The copy part is casting long to int preventing any testing of larger part ranges.

**Comment by afranken** [comment]
Thank you for your contribution.
Coincidentally, I noticed today too that the response is not XML and was wondering if this even worked. (Same for the getObjectTagging API, BTW)

How did you reproduce these errors?
It'd be great to have local integration tests that find these issues as well. Seems like we're missing some integration tests here :(

**Comment by wwelling** [comment]
https://github.com/wwelling/s3utils/tree/multipart-copy

https://github.com/wwelling/s3utils/blob/multipart-copy/src/test/java/edu/harvard/s3/store/AbstractStoreTest.java#L114

**Comment by wwelling** [comment]
Should be straightforward to add some Spring controller tests. I think `@WebMcvTest(TheController.class)` annotation should simplify.

**Comment by afranken** [comment]
@wwelling 
just released 2.2.1 with your fix, thanks! :)
