### ISSUE TITLE
Support for "from offset" range (e.g., bytes=9500-)

### ISSUE THREAD

**Issue by sfali** [adobe/S3Mock#29]
Hi There,

The `Range` header of with value _bytes=9500-_ is a valid header, which represents start from byte 9500 to the end of file).

Currently code fails to convert such byte range and failed with exception.

This should be easy fix, would you mine if I fork, fix, and create PR.

Regards,

Syed Farhan Ali

**Comment by agudian** [comment]
Hey, thanks! We’d love it if you sent in a PR with a fix 👍
I think we have some tests for the byte range stuff that could be extended withthis case as well...

**Comment by sfali** [comment]
Thanks for accepting PR.

Would you mind pushing change to docker hub as well?

**Comment by timoe** [comment]
Yepp, I'll do.

**Comment by sfali** [comment]
Thanks, this issue can be closed as well.
