### ISSUE TITLE
Support configure AccessKey & Region

### ISSUE THREAD

**Issue by tisonkun** [adobe/S3Mock#305]
Currently, s3 client can access s3mock with any access_key & region config. Is it possible to configure these props for mock?

**Comment by afranken** [comment]
@tisonkun with what goal?
Do you want the S3Mock to reject some incoming connections during the test?
Or do you expect the S3Mock to persist data by accesskey&region so you can use multiple combinations with different levels of access?
There is currently no way to set ACLs or policies on buckets.

**Comment by afranken** [comment]
No reply for almost 12 months, closing.
