### ISSUE TITLE
Can´t assign a list of initial buckets

### ISSUE THREAD

**Issue by juanmorschrott** [adobe/S3Mock#322]
In the documentation states that:

`initialBuckets: list of names for buckets that will be available initially.`

But it actually only supports:

`services.s3.environment.initialBuckets must be a string, number, boolean or null`

**Comment by afranken** [comment]
It's actually a list of strings, not numbers or booleans.
`initialbucket1, initialbucket2` would be a valid setting.
Same for kms keys.

See for example our integration tests:
https://github.com/adobe/S3Mock/blob/main/integration-tests/pom.xml#L134

I'll add examples to the documentation, thanks for mentioning this!

**Comment by juanmorschrott** [comment]
Is it a valid yaml list format? It causes trouble on IntelliJ.

Thanks for answer so fast. Regards

**Comment by afranken** [comment]
Have you tried passing in a String containing the list of names? `"initialbucket1, initialbucket2"`

**Comment by juanmorschrott** [comment]
It works when I tried this way:
 - ib1, ib2
 - "ib1, ib2"
And it doesn´t work this other way:
 - ib1
 - ib2

["ib1", "ib2"]

**Comment by afranken** [comment]
I'll add an example to the readme, thanks.
