### ISSUE TITLE
Support signatureVersion v4 for s3 upload

### ISSUE THREAD

**Issue by Junkern** [adobe/S3Mock#33]
When using `upload()` to upload a file (or stream) to the s3 mock, it always worked, but it did not store any content. When retrieving the stored file, it was of `Content-Length: 0`.

To make it work with the s3mock, I have to add `signatureVersion: 'v2'` to the params when initializing the s3 aws client.

Not sure if that applies to other "upload stuff"-functions as well.

**Comment by timoe** [comment]
Hey @Junkern ,

thanks for the report! Would you be interested in creating a PR to support v4?

**Comment by sveryovka** [comment]
When testing against "master" branch I can't reproduce this problem. Can you please post some sample project to illustrate this issue?

**Comment by timoe** [comment]
@Junkern: Any updates here? This sounds similar to Issue #85. See my comment there, I pushed a branch that modifies upload behaviour. Can you please try that out?

**Comment by timoe** [comment]
Closed due to inactivity
