### ISSUE TITLE
add support for xml responses?

### ISSUE THREAD

**Issue by marcosnils** [adobe/S3Mock#36]
First of all, thanks for putting such effort in this amazing project. We're using it internally in our company to run the integration tests and everything has been running expected.

We're wondering if there's a plan to add support for XML responses soon. The reason for this is because in our particular case we're trying to write a test when we get a `not found` from the `getObject` method, but seems like s3mock return 404 without any XML response which the AWS SDK doesn't understand and just returns a generic 406 code. 

Thanks again. 

/cc @lecocchi

**Comment by timoe** [comment]
Hi @marcosnils,

this is a bug. According to https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html a suitable Http status as well as a error response should be returned. I think we can go for a first fix within getObject but we have to extend S3Mock for error responses in general.

**Comment by marcosnils** [comment]
Nice. Can we go ahead and send a PR for this particular case and then move from there?

**Comment by marcosnils** [comment]
Nice. Can we go ahead and send a PR for this particular case and then move from there?

**Comment by timoe** [comment]
Yes, would be nice of you can provide a PR. We already have stuff for returning error responses. See KMSValidationFilter#doFilterInternal for an example. Based on something like that I'd like to generalize. But let's fix that getObject Bug first.

**Comment by timoe** [comment]
@marcosnils: I implemented basic Error Handling that checks for non existing Buckets and Objects. This commit hits master. Would be nice if you can clone master branch and verify if it fits your expectations.

**Comment by marcosnils** [comment]
@timoe thx for the update. I'll give it a try right away and let u know the results.

**Comment by marcosnils** [comment]
@timoe is there a Dockerfile somewhere to build the image locally to test it?

**Comment by agudian** [comment]
Just `mvn install`, it will also create the Docker image.

**Comment by marcosnils** [comment]
Just realized the image creation is used via maven. Thx @agudian

**Comment by timoe** [comment]
Ok. I'll do a release and close this issue

**Comment by timoe** [comment]
Release is on its way, Issue will be closed
