### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by furlanrapha** [adobe/S3Mock#389]
Is there any plan in the roadmap to create docker images that support ARM?

**Comment by afranken** [comment]
yes, we're planning ARM64 support, but we're not quite there yet. :(
If you build the S3Mock repo on your ARM64 machine, the Docker container is built as an ARM64 container.

See also 
#287 
#313 
#253

**Comment by afranken** [comment]
just released version `2.4.6` which is multi arch for `arm64` and `amd64`.
https://hub.docker.com/r/adobe/s3mock/tags?page=1&ordering=last_updated
