### ISSUE TITLE
Split mock and JUnit rules into separate modules and add JUnit 5 support

### ISSUE THREAD

**Issue by agudian** [adobe/S3Mock#39]
Many users don't use the JUnit rule to start the service and to create the S3 client instance and don't want the dependency, or rather want to use a proper JUnit 5 support.
 
To allow for that, split up the mock application and the JUnit related classes into separate modules, e.g.:
- s3mock
- s3mock-junit4 (dependening on junit 4 and the s3mock fat-jar)
- s3mock-junit5 (dependening on junit 5 and the s3mock fat-jar)

This would be breaking change for users of the JUnit rule, so I suggest doing that change with a major version bump.

**Comment by santthosh** [comment]
@agudian Support for TestNG would be great, I can help

**Comment by agudian** [comment]
> Support for TestNG would be great, I can help

Great, I'll ping you as soon as I have the preliminary refactorings in place. I haven't worked with TestNG in ages, so any help there will be very welcome.

**Comment by agudian** [comment]
@santthosh The refactoring is done, the master branch now has separate modules for junit4 and junit5. Feel free to open a PR for adding a testng variant.
