### ISSUE TITLE
Multi-part upload in S3 has a minimum size allowed of 5MB while S3mock can accept lower values.

### ISSUE THREAD

**Issue by enidgjoleka** [adobe/S3Mock#392]
Hi all,

Thank you for maintaining this project.

We are using S3mock for testing our interaction with S3 and one feature that we use a lot is multi-part upload.
The minimum allowed value in S3 is 5MB, [source](https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html), while S3mock can accept even lower values.

This proved to be an issue for us when releasing in production because S3 rejected our part_size=1MB.

It would be great to port this check in S3mock.

Thank you!

**Comment by afranken** [comment]
@enidgjoleka thanks for the report, I'll look into it. :)
