### ISSUE TITLE
Update heading for repository

### ISSUE THREAD

**Issue by sbrannen** [adobe/S3Mock#46]
### Current

_A simple mock implementation of the AWS S3 API startable as Docker image or JUnit rule_

### Expected

_A simple mock implementation of the AWS S3 API startable as Docker image, JUnit 4 rule, or JUnit Jupiter extension_

**Comment by agudian** [comment]
Well spotted! Thanks!

**Comment by sbrannen** [comment]
Well, @mmerdes actually spotted it. I just reported it. 😉 

Thanks for the quick turnaround!
