### ISSUE TITLE
[Feature] Support Tagging

### ISSUE THREAD

**Issue by santthosh** [adobe/S3Mock#49]
Can we please support?

https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUTtagging.html
https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGETtagging.html

**Comment by agudian** [comment]
Sure!

Would you be open to contribute that feature to speed things up?

**Comment by santthosh** [comment]
Sure @agudian I'll give it a shot and send in a PR

**Comment by santthosh** [comment]
@agudian can you please review and let me know. Thanks

**Comment by agudian** [comment]
@timoe merged it. Thanks, @santthosh!
