### ISSUE TITLE
PutObject returns "201 Created" rather than "200 OK"

### ISSUE THREAD

**Issue by rutarb** [adobe/S3Mock#50]
Hi, 

First of all thank you for even coming up with this project, let alone for making it publicly available, I've been looking for a replacement of fake-s3 that we were using internally for years when I found this repo. We were looking for an alternative that had a fully implemented multipart upload API and voila, this project has it! Good job!

**Now the question:** I see that PUT Object API currently returns a **201 Created** as the response code but Amazon S3 (as well as other S3 like alternatives that we've used in Production) do return a **200 OK** as the response code, is this something you omitted buy mistake or is it a valid response code?
Nothing from the public doc https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html , other than the examples provided, mentions the expected response code, hence my question; all I know is that other implementations, including fake-s3, do return a 200 in case of success.

If it is expected, feel free to close this issue.

Thank you.

**Comment by agudian** [comment]
Thanks for the kind words! 

Our goal is to let the mock behave as much as possible like the real S3 endpoint. 
So if the PUT returns a 200 there, we should do the same (200 on PUT sounds much more reasonable to me anyway 👍).

Would you be interested in contributing a PR for that?

**Comment by rutarb** [comment]
I see @timoe already did. :)

**Comment by timoe** [comment]
@rutarb: Release `2.0.2` is on its way.
