### ISSUE TITLE
Multipart upload is broken

### ISSUE THREAD

**Issue by dizballanze** [adobe/S3Mock#524]
Hello,

I think you missed the last partition check [here](https://github.com/adobe/S3Mock/commit/51d1603bc9af378dfa40702e0fa0f42da0205936#diff-07a3497e4d1d20f99fc76699988605ee852cb60be26491ae2b34d2058c93d7cfR1354)

**Comment by afranken** [comment]
thanks, I'll look into that - I was pretty sure that we have integration tests testing multipart uploads...

**Comment by dizballanze** [comment]
It won't fail in case you are uploading a file each part of which is more than 5mb. Maybe that's the case.

**Comment by afranken** [comment]
Just added a test, everything works as expected.

How did you reproduce this exactly?

**Comment by dizballanze** [comment]
Sorry, my bad :(
That was a bug in our tests.
#https://github.com/aiokitchen/aiohttp-s3-client/pull/12
