### ISSUE TITLE
Add a Spock extension

### ISSUE THREAD

**Issue by rcardin** [adobe/S3Mock#587]
I saw that Spock is missing from the list of the supported testing frameworks. The JUnit4 `@ClassRule` is not working correctly in Spock. So, it would be delightful to have a Spock extension that instantiates the `com.adobe.testing.s3mock.S3MockApplication` class and the S3 client.

I can help in doing so :)

**Comment by afranken** [comment]
@rcardin thank you for your suggestion :)

Unfortunately, including the mock as a dependency and starting it in the unit test has always been problematic:
https://github.com/adobe/S3Mock/issues?q=is%3Aissue+is%3Aclosed+label%3Adependency-problem

I'm recommending to use the Docker container directly, or with https://www.testcontainers.org/ which is super easy to use and completely removes the S3Mock dependencies from the application tests.

See https://github.com/adobe/S3Mock/issues/418#issuecomment-1036356889 for a longer explanation. :)

**Comment by afranken** [comment]
I'll close this issue since we won't implement this extension, see previous comment.
Thanks for the suggestion, though!
