### ISSUE TITLE
Spring Security on The Classpath results in 401

### ISSUE THREAD

**Issue by ateebkhawaja** [adobe/S3Mock#59]
I am running the JUnit4 example given here:

https://github.com/adobe/S3Mock/blob/master/testsupport/junit4/src/test/java/com/adobe/testing/s3mock/junit4/S3MockRuleTest.java

I had alot of dependencies in my project, so I had to go through each one, one by one to narrow it down to this. Once the following dependency is in the POM, the exception below starts to show up. The test has not been modified at all.

The testing project parent:
`	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.1.RELEASE</version>
	</parent>`

Dependency:
`		<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<version>2.0.8.RELEASE</version>
		</dependency>`

JUnit Exception:

> com.amazonaws.services.s3.model.AmazonS3Exception:  (Service: Amazon S3; Status Code: 401; Error Code: 401 ; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
> 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
> 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
> 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
> 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
> 	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1030)
> 	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:967)
> 	at S3MockRuleTest.shouldUploadAndDownloadObject(S3MockRuleTest.java:51)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at com.adobe.testing.s3mock.junit4.S3MockRule$1.evaluate(S3MockRule.java:68)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
>

**Comment by timoe** [comment]
Hi @ateebkhawaja,

I setup a Maven Project with that dep. constellation
```
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.0.1.RELEASE</version>
  </parent>

  ...

  <dependencies>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
      <version>1.11.321</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.security.oauth</groupId>
      <artifactId>spring-security-oauth2</artifactId>
      <version>2.0.8.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>com.adobe.testing</groupId>
      <artifactId>s3mock-junit4</artifactId>
      <version>2.0.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

and was able to reproduce it. Smells like a Bug, I'll take care.

**Comment by timoe** [comment]
@ateebkhawaja: I found a potential fix. To verify this, can you please pull this branch: https://github.com/timoe/S3Mock/tree/fix/disable-security-auto-config. It excludes SecurityAutoConfiguration from Spring Boot Application:

```
@Configuration
@EnableAutoConfiguration(exclude = {SecurityAutoConfiguration.class })
@ComponentScan
public class S3MockApplication {
```

an I got my local test running.

**Comment by ateebkhawaja** [comment]
@timoe I tested this locally with my project and it is working now. Thanks.

**Comment by timoe** [comment]
release is on its way @ateebkhawaja
