### ISSUE TITLE
Multipart md5 hash calculation is incorrect

### ISSUE THREAD

**Issue by kkuo** [adobe/S3Mock#66]
It looks like in `FileStore.java` the ETag is calculated as the md5 of the entire file. This isn't correct according to this answer on stack exchange: https://stackoverflow.com/questions/12186993/what-is-the-algorithm-to-compute-the-amazon-s3-etag-for-a-file-larger-than-5gb

If I understand correctly for a multipart upload the hash should really be:

md5 of concatenated byte arrays of each part's etag, appended by a `-N` where `N` is the number of parts.

**Comment by timoe** [comment]
Thanks for reporting @kkuo. Would you like to contribute that?

**Comment by kkuo** [comment]
I don't have it fixed locally just bypassed the bug in my code, but I can make a PR for it, and with the other issues that I have found.

**Comment by kkuo** [comment]
I can work on this in the next few days.

**Comment by mattelacchiato** [comment]
As you can see, I've implemented a fix for this issue.

**Comment by afranken** [comment]
Fix was merged years ago.
