### ISSUE TITLE
NullPointerException running the S3MockContainer in Java Unit testcases

### ISSUE THREAD

**Issue by DipalPrajapati** [adobe/S3Mock#682]
I am getting null pointer on S3Client , using https://github.com/adobe/S3Mock/blob/main/testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerJupiterTest.java
`        client.createBucket(CreateBucketRequest.builder().bucket(BUCKET).build());`

**Comment by afranken** [comment]
@DipalPrajapati do you have an example repo to reproduce this?

**Comment by afranken** [comment]
@DipalPrajapati you opened a similar issue at the same time as this one, but closed it immediately.
Did you solve this issue as well?

I'll close this issue, please feel free to re-open or open a new issue with a reproducer :)
