### ISSUE TITLE
Transfer manager multipart upload degradation

### ISSUE THREAD

**Issue by pkukharenka** [adobe/S3Mock#694]
https://github.com/adobe/S3Mock/issues/524

This PR made a degradation in upload multipart flow. Upload parts might be empty if this is very beginning of multipart upload. Whenever you start uplaoding file as multi parts, s3 transfer manager checks if there are parts that were already uploaded by calling:
`PartListing parts = s3.listParts(listPartsRequest)` 

0 parts doesn't mean that upload is invalid, it just means that no parts were uploaded yet.

**Comment by afranken** [comment]
Just released `2.4.14` with the fix. :)
