### ISSUE TITLE
Support for CORS headers

### ISSUE THREAD

**Issue by vroudge** [adobe/S3Mock#74]
Hello!

I'm trying to use this to test a browser-based uploader. I get issues related to CORS. Is there anyway to set the cross origin headers with S3Mock ?

**Comment by agudian** [comment]
We don’t have that, yet. But I bet it can be added through Spring Boot...

**Comment by vroudge** [comment]
That would be brilliant. I'm not a Java person myself, but I'll keep looking at this ticket, it's a very interesting feature.

**Comment by timoe** [comment]
@vroudge: Spring (Boot) offers CORS configuration (see: https://spring.io/blog/2015/06/08/cors-support-in-spring-framework). The most simple way to enable each and every origin would be to add a global mapping for each and every API S3Mock provides. 

My current idea is to enabled origins and/or API endpoints via configuration. Before doing that, can give please give the usecase you're working on? Do you have any examples, code-snippets that let me verify this for your usecase? 

Thanks
Timo

**Comment by haffla** [comment]
Is there an ETA for this @timoe?

**Comment by afranken** [comment]
version 2.2.2 adds CORS headers for all origins (wildcard pattern).
Hope that helps.

**Comment by mikemonteith** [comment]
This change results in two identical `Access-Control-Allow-Origin: *` headers being set on the `GET` controller, which gives a browser error "Cross-Origin Request Blocked: .... (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed)."

There was already a cross origin http header being set here https://github.com/adobe/S3Mock/blob/afbce436ea5e4354ffa6780c71c115b6874266c7/server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java#L608

**Comment by afranken** [comment]
@mikemonteith thx for alerting me - I'll remove the explicit setting you mentioned, just opened a PR :)

**Comment by mikemonteith** [comment]
Wow @afranken that was fast!

**Comment by afranken** [comment]
@mikemonteith thanks for providing the solution with the report :) 

I was just merging the latest dependabot updates and then release, so it was easy to add in this trivial fix.
We unfortunately do not have any browser-related tests, and I was too lazy to manually test if the CORS headers are actually working. Maybe I'll add asserts to one of the integration tests when I find the time...
