### ISSUE TITLE
limit spring application executors number

### ISSUE THREAD

**Issue by bigman3** [adobe/S3Mock#75]
upon application start, it initializes some executor threads, 1 for each vCore AFAIU.

If initialized with  
S3MockApplication.start(props), 

what  key-value should be passed to configure executors number?

My use case is non parallel requests to S3.

Thanks

**Comment by timoe** [comment]
Hi @bigman3,

S3Mock uses an embedded Tomcat, currently 8.5.29. You can limit the number of max Tomcat Threads setting `server.tomcat.max-threads`, e.g. `-Dserver.tomcat.max-threads=10`. 

How do you make use of S3Mock? Start it by your own? Use the Docker image? Use JUnit/TestNG integration?

Hope that helps
Timo

**Comment by bigman3** [comment]
@timoe 

in JUnit test setup , I do 
_S3MockApplication.start(propertiesMap)_

where  propertiesMap contains settings for port, initial bucket etc.

so I should set  "server.tomcat.max-threads"  JVM environment variable, to the desired value?
Or I can somehow pass a key-value setting via propertiesMap ?

**Comment by timoe** [comment]
I set `-Dserver.tomcat.max-threads=1` as a VM option and debugged it down to the point where Tomcat-Connector was configured for the max thread count. 

Unfortunately passing properties 
```
"server.tomcat.max-threads"
"server.tomcat.min-spare-threads"
```

via `S3MockApplication.start(propertiesMap)` will not work as the start method takes the commandline arguments S3 Mock is started with but not the environment properties which are needed to configure e.g. `server.tomcat.max-threads`. 

However, there are several options. You can either set `-Dserver.tomcat.max-threads=1` resp. `-Dserver.tomcat.min-spare-threads=1` via VM option or we can extend `S3MockApplication#start` for taking those properties including JUnit/TestNG Integration types. 

Are you interested in sending a PR?

Timo

**Comment by timoe** [comment]
Closing this one, will be covered by https://github.com/adobe/S3Mock/issues/77
