### ISSUE TITLE
S3Mock Configuration Options

### ISSUE THREAD

**Issue by timoe** [adobe/S3Mock#77]
We had to requests regarding configuring S3Mock regarding usage of the `silent` parameter (https://github.com/adobe/S3Mock/issues/76) and Tomcats amount of threads (https://github.com/adobe/S3Mock/issues/75). Today there are some options to configure those (but there's no way to choose the option. So, `silent` can only be configured programmatically, Tomcat threads can be set via VM argument. 

Let's introduce a way to harmonise and open configuration options. When done users can pass their config via environment variable, via VM argument and via command line. This include documentation of existing configuration options.

**Comment by afranken** [comment]
closing, the two suggestions were implemented, when we need more, we'll open more issues.
