### ISSUE TITLE
ListObjectsV2 etags should be quoted, but are not

### ISSUE THREAD

**Issue by robd** [adobe/S3Mock#801]
From real S3, the ETag value is surrounded by quotes (ie the java string looks like `"\"99f2fdceebf20fb2e891810adfb0eb71\""`) when calling ListObjectsV2, but S3Mock does not include quotes. 

For other methods, eg `GetObjectRequest`, S3Mock does correctly put the quotes in the ETags.

Possibly related: https://github.com/adobe/S3Mock/commit/7f578e56a8b1e626d923efb7ea547b625f2900da
Also: https://github.com/aws/aws-sdk-java-v2/issues/1417#issuecomment-531992054

**Comment by afranken** [comment]
@robd thanks for the report - I thought I caught them all in 7f578e5 ;)
Will release in a couple of minutes.

**Comment by afranken** [comment]
Just released 2.6.1 for your convenience. :)
