### ISSUE TITLE
Are the ports the container listens on configurable?

### ISSUE THREAD

**Issue by khpeek** [adobe/S3Mock#842]
As far as I can tell from the documentation on Docker Hub (https://hub.docker.com/r/adobe/s3mock/), the exposed ports for the `adobe/S3Mock` container are fixed and set at 9090 and 9191 for HTTP and HTTPS, respectively. I would like to be able to configure the ports the container listens on, is this possible? If not, perhaps it could be made so (through an environment variable or command argument)?

**Comment by afranken** [comment]
@khpeek 
what you're looking for is a feature of the [`docker run` command](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose)

The ports of the application running inside the Docker container are 9090 and 9191, it's up to you to declare which ports to map them to on your system.

For example:
```
$ docker run -p 9090:9090 -p 9191:9191 -t adobe/s3mock
[...]
$ curl http://localhost:9090/
<ListAllMyBucketsResult><Owner><ID>79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be</ID><DisplayName>s3-mock-file-store</DisplayName></Owner><Buckets/></ListAllMyBucketsResult>
```

and

```
$ docker run -p 9099:9090 -p 9191:9191 -t adobe/s3mock
[...]
$ curl http://localhost:9099/
<ListAllMyBucketsResult><Owner><ID>79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be</ID><DisplayName>s3-mock-file-store</DisplayName></Owner><Buckets/></ListAllMyBucketsResult>
```

**Comment by afranken** [comment]
If you're using a plugin or library to execute the container, that will usually provide a way to add a port mapping as well.
fabric8 docker-maven-plugin:
https://github.com/adobe/S3Mock/blob/main/integration-tests/pom.xml#L139

TestContainers:
https://github.com/adobe/S3Mock/blob/main/testsupport/testcontainers/src/main/java/com/adobe/testing/s3mock/testcontainers/S3MockContainer.java#L55

**Comment by afranken** [comment]
one addition:

If you were to start the S3Mock directly using Java (so not the S3Mock Docker container), then you can set the ports as well.
This uses the default ports:
https://github.com/adobe/S3Mock/blob/main/testsupport/junit5/src/test/java/com/adobe/testing/s3mock/junit5/sdk2/S3MockExtensionProgrammaticTest.java#L43

but that builder class exposes the following methods as well: `withHttpPort(int)`, `withHttpsPort(int)`.
This will make S3Mock start up on different ports than the default HTTP=9090 and HTTPS=9191.
