### ISSUE TITLE
Deleting multiple objects fails with status code 415

### ISSUE THREAD

**Issue by wmnnd** [adobe/S3Mock#87]
Hey there,

I’m trying the S3Mock Docker image to automate testing of an Elixir application that uses S3.

I have noticed that there is one operation that consistently fails with S3Mock while it works fine with other implementations of the S3 API: Deleting multiple objects.

When I try deleting multiple objects, here is the response I get:
```
body: "",
headers: [
      {"Accept",
       "application/xml, application/x-www-form-urlencoded, application/octet-stream, text/plain, text/xml, application/*+xml, multipart/form-data, application/json, application/*+json, */*"},
      {"Content-Length", "0"},
      {"Date", "Thu, 19 Jul 2018 22:31:36 GMT"}
    ],
status_code: 415
```
This is the request body that was sent:
```
<?xml version=\"1.0\" encoding=\"UTF-8\"?><Delete><Object><Key>bar</Key></Object></Delete>"
```
Nothing was logged to the Docker logs. Deleting the same file with a simple `DELETE` request works fine.

Is this functionality currently not supported?
I saw there is a `BatchDeleteRequest` class which I assume is intended for this, but I haven’t digged any deeper yet.

**Comment by agudian** [comment]
`BatchDeleteRequest` is supported, and the 415 smells like we are either too strict with the required Content-Type header, or your test is not sending the right one. Which headers do you send in the request?

**Comment by wmnnd** [comment]
Here is the debug information from ExAws:

```
URL: "http://172.17.0.2:9090/foo/?delete"

HEADERS: [
  {
    "Authorization",
    "AWS4-HMAC-SHA256 Credential=/20180724/eu-central-1/s3/aws4_request,SignedHeaders=content-length;content-md5;host;x-amz-content-sha256;x-amz-date,Signature=5e9a8670ccb1a0a7b6f2e8b425eb2239d207d5c330a690ab154374ee06d21857"
  },
  {
    "host",
    "172.17.0.2:9090"
  },
  {
    "x-amz-date", 
    "20180724T200210Z"
  },
  {
    "content-length", 
    467
  },
  {
    "content-md5",
    "lGN9oo/ch85VPi6Oy+/l9w=="
  },
  {
    "x-amz-content-sha256",
    "954469a392adb8678a0f88d4358b3cffbc7dc180798de953d62230c8feef7922"
  }
]

BODY: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Delete><Object><Key>delete-scope/list-files-scoped-test_1.tmp</Key></Object><Object><Key>delete-scope/list-files-scoped-test.tmp</Key></Object><Object><Key>delete-scope/list-files-scoped-test_3.tmp</Key></Object><Object><Key>delete-scope/list-files-scoped-test_2.tmp</Key></Object><Object><Key>delete-scope/list-files-scoped-test_5.tmp</Key></Object><Object><Key>delete-scope/list-files-scoped-test_4.tmp</Key></Object></Delete>"
```

**Comment by agudian** [comment]
The AWS Java SDK also sets `Content-Header: application/xml`... 😕

Let's see if we find a solution for this, as we don't explicitly require a content-type in our code...

**Comment by wmnnd** [comment]
Thank you for looking into this.
The S3 docs don’t mention the `Content-Type` header for requests, though:
https://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html

**Comment by timoe** [comment]
It definitely works when passing "Content-Type: application/xml". 
`curl -XPOST --data '<?xml version="1.0" encoding="UTF-8"?><Delete><Object><Key>myFile-1</Key></Object><Object><Key>myFile-2</Key></Object></Delete>' http://localhost:9090/bucket-a/\?delete` 

Debugging this a bit shows that invocation goes along the same code path either setting "Content-Type: application/xml" or not setting it. @wmnnd: If you set the "Content-Type: application/xml" does it work then? 

I wonder @agudian if we can default content type somehow as, right now, we're only accepting application/xml.

**Comment by scooper91** [comment]
Is there any update on this? We're seeing the same issue when trying to delete multiple objects using the JS AWS SDK.

**Comment by agudian** [comment]
We didn't find a way to handle that, yet. But tbh, we also didn't look too hard into it. I'm gonna try around a little bit tomorrow to see if anything works...

**Comment by agudian** [comment]
Okay, we made a fix and the release `2.1.1` is on it's way to Docker hub and Maven central (had some trouble with the release automation, so it took a while).

Please check if that works for you now and reopen if necessary.

**Comment by scooper91** [comment]
Thanks for that! The deleting multiple objects now doesn't fail, but we've noticed a couple more problems which we'll make new issues for.

**Comment by scooper91** [comment]
I've made three issues for the problems we're now having: #119, #120, #121.
