### ISSUE TITLE
Running out of heap space for large files

### ISSUE THREAD

**Issue by jakelamotta** [adobe/S3Mock#922]
Is it possible to configure the container to run with a larger max heapspace than the current 128Mb? I am running the 2.8.0 version of the S3Mock.

**Comment by afranken** [comment]
Just released 2.10.0, now S3Mock uses the resources available to the container.
The JVM will automatically use 50% of the available memory.

If you wanted to give 1GB to the S3Mock, you'd have to run `--memory="2g"`.

**Comment by afranken** [comment]
Also, I just released 2.10.1 which fixes a bug where incoming request bodies would be read fully into memory.
With 2.10.1, I am able to persist large files (multiple GBs) when running S3Mock with a 64MB heap.
