### ISSUE TITLE
Create bucket if it doesn't exist

### ISSUE THREAD

**Issue by MiguelSCruz** [adobe/S3Mock#927]
Is there an option to create the bucket if it doesn't exist during write operations?

**Comment by afranken** [comment]
This application implements the S3 API.
Is this possible in S3? Do you have an API reference?

**Comment by MiguelSCruz** [comment]
AFAIK it's not possible, but usually you have an infrastructure configuration that creates the buckets before an app starts using it. It would be helpful when using the docker image to run tests against not having to worry about creating the buckets before,
But I get your point of mimicking the actual S3 API.

**Comment by afranken** [comment]
Did you see https://github.com/adobe/S3Mock#configuration ?
You can tell S3Mock which buckets to create when it starts up. :)
